
export const actionTypes = {
    IS_FAVORITE: 'IS_FAVORITE',
    ADD_FAVORITE: 'ADD_FAVORITE',
    REMOVE_FAVORITE: 'REMOVE_FAVORITE',
    CHANGE_THEME: 'CHANGE_THEME',
    FETCH_START: 'FETCH_START',
    FETCH_ERROR: 'FETCH_ERROR',
    GET_DATA: 'GET_DATA',
  };
  